name: 获取ip

on:
  schedule:
    - cron: '0 21 * * *'  # UTC时间21点 = 北京时间次日5点
  workflow_dispatch:  # 允许手动触发

jobs:
  overwrite-txt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch content and overwrite file
        run: |
          # 抓取目标TXT并覆盖根目录的addressesapi.txt，保持原结构
          curl -sSL https://zip.cm.edu.kg/all.txt -o addressesapi.txt

      - name: Auto commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto overwrite addressesapi.txt (daily update)"
          file_pattern: "addressesapi.txt"
