name: 抓取JSON

on:
  schedule:
    - cron: '0 21 * * *'  # UTC 21点 = 北京时间次日5点
  workflow_dispatch:  # 支持手动触发

jobs:
  extract-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Extract IP:Port via jq (with error handling)
        run: |
          curl -sSL https://zip.cm.edu.kg/all.json | jq -r '
            # 先过滤出对象类型的条目，再匹配iata，避免字符串条目报错
            .[] | select(type == "object" and (.iata == "AMS" or .iata == "KIX" or .iata == "NRT" or .iata == "HKG")) | 
            .ips[] | "\(.ip):\(.port)#\(.city)"
          ' > addressesapi.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto extract IP:Port for AMS/KIX/NRT/HKG"
          file_pattern: "addressesapi.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
