name: 获取JSON

on:
  schedule:
    - cron: '0 21 * * *'  # UTC 21点 = 北京时间次日5点
  workflow_dispatch:  # 支持手动触发

jobs:
  extract-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 用内置令牌获取推送权限
          fetch-depth: 0  # 拉取完整历史，避免分支关联问题

      - name: Extract IP:Port via jq (with error handling)
        run: |
          curl -sSL https://zip.cm.edu.kg/all.json | jq -r '
            .[] | select(type == "object" and (.iata == "AMS" or .iata == "KIX" or .iata == "NRT" or .iata == "HKG")) | 
            .ips[] | "\(.ip):\(.port)#\(.city)"
          ' > addressesapi.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto extract IP:Port for AMS/KIX/NRT/HKG"
          file_pattern: "addressesapi.txt"
          push_options: "--set-upstream origin main"  # 显式关联推送分支
