name: 获取JSON

on:
  schedule:
    - cron: '0 21 * * *'  # UTC 21点 = 北京时间次日5点
  workflow_dispatch:

jobs:
  extract-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Extract IP:Port (fix JSON path)
        run: |
          curl -sSL https://zip.cm.edu.kg/all.json | jq -r '
            # 目标数组是.data，iata/city在.locations下，port是数组需取第一个元素
            .data[] | select(type == "object" and .locations.iata in ["AMS", "KIX", "NRT", "HKG"]) | 
            "\(.ip):\(.port[0])#\(.locations.city)"
          ' > addressesapi.txt

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add addressesapi.txt
          git commit -m "Auto extract IP:Port for AMS/KIX/NRT/HKG" || echo "No changes"
          git push origin main
